PRODUCT_NAME      = "//h1[@itemprop='name']"
QUANTITY_WANTED   = "//input[@id='quantity_wanted']"
PLUS_ICON         = "//i[@class='icon-plus']"
SIZE_DROPDOWN     = "//div[@class='attribute_list']/div[@id='uniform-group_1']/select"
COLOUR_SELECT     = "//ul[@id='color_to_pick_list']/li/a[@name='~~~']"
COLOUR_SELECTED   = "//ul[@id='color_to_pick_list']/li[@class='selected']/a"
ADD_TO_CART       = "//span[text()='Add to cart']"
SUCCESS_MESSAGE   = "//h2[text()[contains(normalize-space(.), 'Product successfully added to your shopping cart')]]"
CHECK_OUT         = "//span[text()[contains(normalize-space(.),'Proceed to checkout')]]"